# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-DialUpManager
version:      0.03
version_from: DialUpManager.pm
installdirs:  site
requires:
    Test:                          0
    Test::More:                    0
    Wx:                            0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
